### ISSUE TITLE
Supported Eco-Cute ?

### ISSUE THREAD

**Issue by sympapa** [scottyphillips/echonetlite_homeassistant#151] opened 2023-12-09 23:12 UTC
Hello everyone.

Is this integration supported Eco-Cute(electricWaterHeater) ?

I moved to new house 1 month ago and I am using an Eco-Cute first time for me.
My Eco-cute is Mitsubishi SRT-S466A+RMCB-H6SE-T and after connecting to this integration, 17 sensor entities working.
But, there are no sensors for power consumption there and no entities for operation.

I would like to know this is normal behavior or I have failed to connect.
If anyone has ever connected an Eco-Cute, I would appreciate a reply as to how it behaves.

Thank you.

**Comment by scottyphillips-work** [comment] 2023-12-11 04:35
Hi There. The pychonet library doesn't have a module for ElectricWaterHeater. When I get a chance I will create one sometime in the next week. In the meantime can you switch on debugging of the custom component and post the log output here?

**Comment by sympapa** [comment] 2023-12-12 15:03
@scottyphillips-work

Hello !
Thanks for your reply.
This custom component is very useful for me and I appreciate your great work.

I have just enabled debug logging of this custom component.
I am not used to reporting HA debug logs but I will try that this weekend.
Are there any operations that should be performed during logging?
Do I need to extract the logs with a specific word?

I would be very happy if this custom component supported Eco-cute, but prioritise time with your family.

Thanks.

**Comment by scottyphillips-work** [comment] 2023-12-12 21:49
Hello! Just go to Settings -> System -> Logs and copy the text into a text file and attach here.

**Comment by scottyphillips** [comment] 2023-12-16 03:01
Hi. I have stared work on this a little bit. I would still like to see your logs, but when you get a chance can you: 
-> go to HACS -> Integrations 
-> click ECHONETLite platform 
-> click the three dots in the top right corner 
-> click redownload 
-> select 'show beta versions'
-> select 'master' version.
-> Download. 
This will give you the latest working version which is running the updated pychonet library with support for your Electric Water Heater.
Let me know what sensors are working for your Eco-Cute, and post me those logs!

**Comment by sympapa** [comment] 2023-12-17 15:13
@scottyphillips-work

Hello!
There doesn't seem to be much information on this integration - is this the right log?
If you need the full log, I can upload it at a later date.
[231217log.txt](https://github.com/scottyphillips/echonetlite_homeassistant/files/13696612/231217log.txt)

Thank you for the update.
I will install the beta version now and give you feedback at a later date.

Thanks

**Comment by sympapa** [comment] 2023-12-17 15:42
@scottyphillips-work

I have installed the master version. It is not clear if the items are exactly the same, but 17 sensors are available as before.
Available sensors are as follows

Automatic bath water heating mode setting
Automatic water heating setting
Bath operation status monitor
Bath water temperature setting
Bath water volume setting 3
Daytime reheating permission setting
Hot water supply status
Manual bath hot water addition function setting
Manual slight bath water temperature lowering function setting
Measured amount of water remaining in tank
Measured temperature of water in water heater
Operation status
Tank capacity
Tank operation mode setting
Temperature of supplied water setting
Water heater status
Water heating temperature setting

I will upload the logs after a few days, but is there anything I should do for verify?

**Comment by sympapa** [comment] 2023-12-17 23:50
Mislabelled. Sorry.

**Comment by sympapa** [comment] 2023-12-17 23:51
Mislabelled. Sorry.

**Comment by nao-pon** [comment] 2024-01-31 11:52
@sympapa Can you try my edge branch? It is not a stable version yet, so please make a full backup before trying it. If everything goes well, the sensor, switch, select, and time input entities will be configured.

For the Number input entity, we need to define a setting in ENL_OP_CODES in const.py, but we haven't configured it yet.

- https://github.com/nao-pon/echonetlite_homeassistant

**Comment by nao-pon** [comment] 2024-02-07 15:55
@sympapa The double registration issue has been fixed in 3.8.0-Beta5. Currently edge and beta are the same.
Entities with Unknown data may have valid specifications, but the data may not actually be published.

Power measurement is not yet implemented.

For now, I would like to see what kind of data form your device, so please try the following.

- Enable debug logging on the echonetlite integration page.
- Restart HA.

After about an hour, you can disable debug logging and download the logs. Please attach the log as a file.

**Comment by sympapa** [comment] 2024-02-07 21:06
@nao-pon

Thank you for your reply !
I I will do that this weekend.

Thanks

**Comment by nao-pon** [comment] 2024-02-08 15:25
@sympapa Support for Electric water heater is almost complete in Version 3.8.0-beta6. However, it has not been tested on an actual device.

Please help us with the operation verification! 🤝

**Comment by sympapa** [comment] 2024-02-10 00:33
@nao-pon
After my recent comment, I restored the full backup and went back to 3.8.0-beta4 and updated to 3.8.0-beta6 today, but issue #165 occurred.
Five Mitsubishi air conditioners doesn't have that problem, but Sharp air conditioner and Omron solar power conditioner have that problem.

I have created so many sensors from Omron solar entities, that it would take a lot of time to reconfigure them from scratch.
So sorry, I have restored backup again and I have not checked the behaviour related to the Ecocute in 3.8.0-beta6.

Are there any solutions for this issue?

**Comment by nao-pon** [comment] 2024-02-10 01:15
To avoid issue #165, you must update from Version 3.7.9 or earlier to Version 3.8.0-beta5 or later.
However, if you remove the device yourself in the future and reconfigure it, the same problem will occur only once.
If possible, we recommend removing and reconfiguring the device at this stage. Even if you do that, the entity ID will remain the same and the prediction will not affect previous history, automation, etc. Please perform a full backup and then try again.

**Comment by sympapa** [comment] 2024-02-10 21:07
@nao-pon
Hello !
Thank you for your reply.

Unfortunately, after installing Beta-6, the entity ID has changed as a result of removing and reconfiguring the Omron solar.
My Omron solar power conditioner is "KP-MU1P-SET" and there are two devices on one IP address.
At version 3.8.0-beta4 or earlier they were "Omron_solar_panel_metering" and "Omron_solar_power_generation".(not changed from the default)
But, the result of the reconfiguration on 3.8.0-Beta6 is "omron solar" for both devices.

I decided to manually reconfiguration using a new name the previously created sensor.
Due to the time required for this work, testing of the Ecocute will be carried out at a later date.
Please wait for a while.

The amount of ecocute entities has been reduced from 21 to 20 on 3.8.0-beta6.
The number of numeric input entities has increased from two to three and the 2 selector entities ("tankOperationMode","automaticWaterHeating") has been lost.

Thanks.

**Comment by sympapa** [comment] 2024-02-10 23:50
@nao-pon 
In 3.8.0-beta6, the Omron solar entities seems to has problems that it did not has before.
One example, the unit for "measured_cumulative_amount_of_electric_energy_normal_direction" should be "Wh", but is instead "kWh".
I restored the backup again.

But, I foolishly hadn't thought to test it on the other Raspberry Pi. 😵
I have set up a test environment and will upload the logs in the today.👍

**Comment by sympapa** [comment] 2024-02-11 01:11
@nao-pon

I tested the Ecocute on 3.8.0-beta6.
- The three numeric input entities seems to working fine.
- 2 selector entities ("tankOperationMode","automaticWaterHeating") has been lost.
- "cumulativeElectricEnergy" still does not exist.

Maybe the data for "tankOperationMode" and "automaticWaterHeating" are published.
The selector options for "tankOperationMode" are "standard/saving/extra" and those for "automaticWaterHeating" are "auto/manualHeating/manualNoHeating".

Please find the log in the attachment.
[home-assistant_echonetlite_2024-02-11T00-59-58.805Z.log](https://githubThanks.

Thank you😀

**Comment by nao-pon** [comment] 2024-02-12 14:50
@sympapa The definitions of "Expected electric energy at daytime heating shifttime 1" and "Consumption of electric energy per hour 1" were missing, so I added them. Can you try it on my edge version?

Also, there seems to be no problem with Input Select, but what exactly is it?

**Comment by sympapa** [comment] 2024-02-12 23:37
@nao-pon 
Hello!
I tried clearing my browser cache, but that didn't improve.
I also searched for the entities "Mitsubishi Electric GT-WLNA2" but still not found that 2 input select entities.
Sensor entities of "tankOperationMode" and "automaticWaterHeating"  are exist and working, but the input select entities does not exist.

These are on 3.8.0-beta6.
I will try the Edge version at a later date.

Thank you !

**Comment by nao-pon** [comment] 2024-02-16 12:06
@sympapa 

> In 3.8.0-beta6, the Omron solar entities seems to has problems that it did not has before.
One example, the unit for "measured_cumulative_amount_of_electric_energy_normal_direction" should be "Wh", but is instead "kWh".

According to the ECHONET Lite specifications, the unit is "kWh". According to your logs for example

  - Measured cumulative amount of electric energy (normal direction) 0xc0(192): 2994871
  - Measured cumulative amount of electric energy (reverse direction) 0xc1(193): 332202
  - Unit for cumulative amounts of electric energy 0xc2(194): 0.001

Therefore, normal direction: 2994871 x 0.001 = 2,994.871 kWh. Is this value (cumulative measurement value) incorrect?

**Comment by sympapa** [comment] 2024-02-17 05:37
@nao-pon 
> According to the ECHONET Lite specifications, the unit is "kWh". According to your logs for example

OK, I understood that the specification is "kWh".
At that time, the "measured_cumulative_amount_of_electric_energy_normal_direction" was 1000 times higher than before (and the automatically calculated electricity costs were also 1000 times higher), but there is no problem with the current test environment.
Maybe I was wrong 😅
If the same problem occurs, I will create a other issue.

Thank you !

**Comment by sympapa** [comment] 2024-02-17 06:41
I have tried your Edge version.
The results of a test are as follows.
・It was not possible to device configure the Eco-Cute with the default settings.
   If the "Maximum number of properties for batch requests" is changed to 30, the device configuration was successful.
・input number entities (other than "temperature_of_supplied_water_setting") and input select entities can be input and are successfully reflected to the device.
   But, the results of operations on the device side are not reflected in those entities.
・"temperature_of_supplied_water_setting", entered value is not reflected to the device.
   But, the results of the operation on the device side are successfully reflected to the entity.
・"cumulativeElectricEnergy" does not exist yet.
・For entities with status "unknown", my Ecocute may not support them.

Please find the log in the attachment.
[home-assistant_echonetlite_2024-02-17T06-39-28.721Z.log]
(https://github.com/scottyphillips/echonetlite_homeassistant/files/14317988/home-assistant_echonetlite_2024-02-17T06-39-28.721Z.log)
![ecocute-1](https://github.com/scottyphillips/echonetlite_homeassistant/assets/82555437/c4d151b3-6407-4e0b-8140-db166d74e648)
![ecocute-2](https://github.com/scottyphillips/echonetlite_homeassistant/assets/82555437/f484872f-de12-4842-976b-9503562b47fa)
![ecocute-3](https://github.com/scottyphillips/echonetlite_homeassistant/assets/82555437/4a3541b1-0b3d-4766-978d-c636752c37ae)

**Comment by nao-pon** [comment] 2024-02-17 12:47
@sympapa There was a simple syntax error in getting the value of `0xCC: Consumption of electricenergy per hour 1`, so I fixed it. You can try it on edge 0a5fc44. Others are under investigation.

**Comment by nao-pon** [comment] 2024-02-17 13:05
The hot water temperature setting was changed from a maximum of 70°C to 90°C. You can try it on edge 75602ce.

**Comment by nao-pon** [comment] 2024-02-17 13:08
Looking at the log, it seems that reception from the device is unstable. If possible, restarting the device may improve the situation.

**Comment by sympapa** [comment] 2024-02-17 21:56
@nao-pon 
Hi !

I have tried the current latest version. (Where can I find the version?)
It is not certain, but rebooting the Raspberry Pi seems to have improved reception.
The device configuration could be done with the default settings.
Test result are below.

No entity has a status of "unknown", all entities have value.

"Automatic bath water heating mode setting" input select entity does not exist, it has been lost.

"cumulativeElectricEnergy" still does not exist.

The "ecocute_temperature_of_supplied_water_setting" input select entity working fine in both directions.

Three input number entities seems to working fine in both directions.
*The "temperature_of_supplied_water_setting" input number entity does not work above 50°C, but this may be due to Ecocute specifications.
Something similar was mentioned here.
[https://qiita.com/banban525/items/520caead4f5f8dbb9ced](https://qiita.com/banban525/items/520caead4f5f8dbb9ced)

Sorry, other checks have not been made, or it is not even clear which operation on the Eco-Cute side are linked to which entities in the first place.

Please find the log in the attachment.
[home-assistant_echonetlite_2024-02-17T21-54-49.032Z.log](https://github.com/scottyphillips/echonetlite_homeassistant/files/14320284/home-assistant_echonetlite_2024-02-17T21-54-49.032Z.log)

![ecocute-a](https://github.com/scottyphillips/echonetlite_homeassistant/assets/82555437/7d44264d-f0ff-4240-bca1-c73729c0722c)
![ecocute-b](https://github.com/scottyphillips/echonetlite_homeassistant/assets/82555437/856ac84c-2478-4468-83c2-074b378f3e86)

**Comment by nao-pon** [comment] 2024-02-18 15:32
> "Automatic bath water heating mode setting" input select entity does not exist, it has been lost.

According to the logs, there should be no particular problem, so I don't know the cause. It may have been unstable during setup...

The available data seems to be working for the most part. However, there was a problem where the input entity and sensor entity overlapped, so I fixed it with edge (ba75b12).

The installed version of edge is displayed on the HACS screen.
![240219-002210](https://github.com/scottyphillips/echonetlite_homeassistant/assets/1412630/c9b7c661-6856-4025-b82c-1ba8a553787a)

**Comment by sympapa** [comment] 2024-02-22 23:40
Hello !

I have tried "e8edc15".
This time there are two logs.

The "Automatic bath water heating mode setting" input select entity does not appear after setting and deleting the Eco-Cute 10 times with the default settings.
But, if set the "Maximum number of properties for batch requests" to "30" and reload, the "Automatic bath water heating mode setting" input select entity appears.
On the other hand, if the "Maximum number of properties for batch requests" is left at "30", the status of most entities are "unknown".
After that, after setting the 'Maximum number of properties for batch requests' to "1", ecocute could no longer be configured.
These are the operations in the first log.
[home-assistant_echonetlite_2024-02-22T22-36-10.310Z.log](https://github.com/scottyphillips/echonetlite_homeassistant/files/14380294/home-assistant_echonetlite_2024-02-22T22-36-10.310Z.log)

Next, the HA was restarted, the Eco-Cute was configured, the "Maximum number of properties for batch requests" was set to "30" and reloaded, "Automatic bath water heating mode setting" input select entity appeared.
Then set the "Maximum number of properties for batch requests" to ”10" and reload, the status of all entities started to working.
These are the operations in the 2nd log.
[home-assistant_echonetlite_2024-02-22T23-10-12.776Z.log](https://github.com/scottyphillips/echonetlite_homeassistant/files/14380295/home-assistant_echonetlite_2024-02-22T23-10-12.776Z.log)

That means, if one configuration step is added, the most entities working fine.

I have a question.
"CumulativeElectricEnergy" does not exist yet, Has that been implemented yet?
When "CumulativeElectricEnergy" is working, I want to try it on my main HA environment.😉

Thank you !

**Comment by nao-pon** [comment] 2024-02-23 15:41
@sympapa Thank you for your cooperation in the verification!

I updated edge. The cause of the unstable status of batch requests is not clear, but I tried setting [an interval of 500ms when sending batch requests](https://github.com/scottyphillips/echonetlite_homeassistant/commit/7413a73d146e55e79f97ef644ce894f1f0020f6c). I also believe that "Measured cumulative power consumption" is also enabled.

**Comment by nao-pon** [comment] 2024-02-24 13:02
@sympapa 
> "Measured cumulative power consumption" still does not exist.

I found the cause of this and updated edge. (a62c5af)

**Comment by sympapa** [comment] 2024-02-24 15:58
@nao-pon 
I tried "73e6482"
There is indeed a "Measured cumulative power consumption".
I will do a bit of detailed testing on this version and if there are no major problems I will install it in my main HA environment.

Thank you !

**Comment by sympapa** [comment] 2024-02-24 23:05
@nao-pon
I have started testing "73e6482" on my main HA environment.
I had a bit of trouble resolving the Omron Solar entity id changed due to issue #165, but everything(incl. Eco-cute) seems to be working fine.
But, even in the main HA environment there are problems related to "batch request".

I have a question.
Is that No "unit" in the following three sensor entities for Eco-cute due to the Echonet Lite specifications?
- Measured amount of water remaining in tank
- Measured temperature of water in water heater
- Tank capacity

If that is due to the Echonet Lite specification, I will creat a sensor entities to add the units  in my HA.

Thanks!

**Comment by nao-pon** [comment] 2024-02-25 12:55
@sympapa That's because it wasn't configured. I added and marched on setting the unit of measurement for the missing sensor. 👍

**Comment by sympapa** [comment] 2024-03-02 00:21
@nao-pon 

Hello!
I have been using '3013fce' in my main HA environment from 5 days ago.
A Mitsubishi Eco-Cute, Omron Solar power conditioner, 4 Mitsubishi air conditioners and one SHARP air conditioner are connected.
As far as I am used, there are no problems other than the "batch request" problem when configure the Eco-Cute.
It has been very useful, thank you😉

I think this Ecocute addition can go to the next phase.
If there is something I can help, please feel free to let me know.

Thank you!

**Comment by sympapa** [comment] 2024-03-10 00:08
@nao-pon 

The version I wrote in my previous comment was a mistake.
"e1f0568" is correct.
It is still working fine today for Eco-cute.

Thanks.

**Comment by nao-pon** [comment] 2024-04-11 14:40
This has been fixed in version 3.8.0 and will be closed. Thanks! 👍

**Closed by nao-pon** 2024-04-11 14:40 UTC
